In [2]:
import pandas as pd, polars as pl, matplotlib.pyplot as plt
import os, subprocess

In [6]:
import datetime as dt

# Data reading

## load all 2024 months of taxi rides

In [3]:
# i am reusing loads used in exercises because they have nice way to prevent from 
#repeated redownload 
DATA_DIR = "data"
if not os.path.exists(DATA_DIR):
    os.mkdir(DATA_DIR)


for month in range(1, 13):
    if not os.path.exists(f"{DATA_DIR}/{month}.parquet"):
        subprocess.run(
            [
                "wget",
                f"https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-{month:02}.parquet",
                "-O",
                f"{DATA_DIR}/{month}.parquet",
            ]
        )


total_size = sum(
    os.path.getsize(f"{DATA_DIR}/{month}.parquet") for month in range(1, 13)
)  # bytes
total_size_mb = total_size // (1024 * 1024)
print(f"Total dataset size: {total_size_mb} MB")

Total dataset size: 660 MB

##    - also load taxi zone lookup data

In [4]:
#also i am borroing this one
if not os.path.exists(f"{DATA_DIR}/taxi_zone_lookup.csv"):
    subprocess.run(
        [
            "wget",
            "https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv",
            "-O",
            f"{DATA_DIR}/taxi_zone_lookup.csv",
        ]
    )

## include only rides starting in 2024 and ending at most at 01.01.2025

In [5]:
df = pl.read_parquet(f"{DATA_DIR}/1.parquet")

In [7]:
df = (
    df.filter
    (
        (pl.col("tpep_pickup_datetime").dt.year() == 2024)
        & (pl.col("tpep_dropoff_datetime").dt.date() <= dt.date(2025,1,1))
    )

)

## ptimize data types, particularly for integers and categorical strings

In [8]:
df.describe()

shape: (9, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ VendorID  ┆ tpep_pick ┆ tpep_drop ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ Airport_ │
│ ---       ┆ ---       ┆ up_dateti ┆ off_datet ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ fee      │
│ str       ┆ f64       ┆ me        ┆ ime       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---      │
│           ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64      │
│           ┆           ┆ str       ┆ str       ┆   ┆ f64       ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 2.964609e ┆ 2964609   ┆ 2964609   ┆ … ┆ 2.964609e ┆ 2.964609e ┆ 2.824447e ┆ 2.824447 │
│           ┆ 6         ┆           ┆           ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0         ┆ … ┆ 0.0       ┆ 0.0       ┆ 140162.0  ┆ 140162.0 │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 1.754203  ┆ 2024-01-1 ┆ 2024-01-1 ┆ … ┆ 0.975632  ┆ 26.801522 ┆ 2.256126  ┆ 0.141161 │
│           ┆           ┆ 7 01:02:0 ┆ 7 01:17:4 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 9.401078  ┆ 6.178878  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 0.432591  ┆ null      ┆ null      ┆ … ┆ 0.218362  ┆ 23.385594 ┆ 0.823267  ┆ 0.487624 │
│ min       ┆ 1.0       ┆ 2024-01-0 ┆ 2024-01-0 ┆ … ┆ -1.0      ┆ -900.0    ┆ -2.5      ┆ -1.75    │
│           ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 00:00:00  ┆ 00:02:42  ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 2.0       ┆ 2024-01-0 ┆ 2024-01-0 ┆ … ┆ 1.0       ┆ 15.38     ┆ 2.5       ┆ 0.0      │
│           ┆           ┆ 9         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 15:59:24  ┆ 16:16:28  ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ 2.0       ┆ 2024-01-1 ┆ 2024-01-1 ┆ … ┆ 1.0       ┆ 20.1      ┆ 2.5       ┆ 0.0      │
│           ┆           ┆ 7         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 10:45:42  ┆ 11:03:57  ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ 2.0       ┆ 2024-01-2 ┆ 2024-01-2 ┆ … ┆ 1.0       ┆ 28.56     ┆ 2.5       ┆ 0.0      │
│           ┆           ┆ 4         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 18:23:56  ┆ 18:40:30  ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 6.0       ┆ 2024-02-0 ┆ 2024-02-0 ┆ … ┆ 1.0       ┆ 5000.0    ┆ 2.5       ┆ 1.75     │
│           ┆           ┆ 1         ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 00:01:15  ┆ 13:56:52  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
df = df.with_columns(
    pl.col("VendorID").cast(pl.Int8),
    pl.col("tpep_pickup_datetime").cast(pl.Datetime),
    pl.col("tpep_dropoff_datetime").cast(pl.Datetime),
    pl.col("passenger_count").cast(pl.Int32),
    pl.col("trip_distance").cast(pl.Float32),
    pl.col("RatecodeID").cast(pl.Int8),
    pl.col("store_and_fwd_flag").cast(pl.Utf8),
    pl.col("PULocationID").cast(pl.Int16),
    pl.col("DOLocationID").cast(pl.Int16),
    pl.col("payment_type").cast(pl.Int8),
    pl.col("fare_amount").cast(pl.Float32),
    pl.col("extra").cast(pl.Float32),
    pl.col("mta_tax").cast(pl.Float32),
    pl.col("tip_amount").cast(pl.Float32),
    pl.col("tolls_amount").cast(pl.Float32),
    pl.col("improvement_surcharge").cast(pl.Float32),
    pl.col("total_amount").cast(pl.Float32),
    pl.col("congestion_surcharge").cast(pl.Float32),
    pl.col("Airport_fee").cast(pl.Float32)
)

# Data cleaning and filtering

## all steps in one until it crashes and burns

In [19]:
df = (
    df.lazy().with_columns(
    pl.col("passenger_count").fill_null(1)
    ).filter(
        pl.col("passenger_count") > 0
    ).with_columns(
        (pl.col("tpep_dropoff_datetime") - pl.col("tpep_pickup_datetime")
         ).dt.total_minutes().alias("trip_duration")
    ).filter(
        pl.col("trip_duration") <=120
    ).with_columns(
        pl.col("passenger_count").clip(upper_bound=6), #thats actually nice function
        pl.col([
            'fare_amount',
            'extra',
            'mta_tax',
            'tip_amount',
            'tolls_amount',
            'improvement_surcharge',
            'total_amount',
            'congestion_surcharge',
            'Airport_fee']).abs()
    ).filter(
        pl.col('fare_amount') < 1000,
        pl.col('extra') < 1000,
        pl.col('mta_tax') < 1000,
        pl.col('tip_amount') < 1000,
        pl.col('tolls_amount') < 1000,
        pl.col('improvement_surcharge') < 1000,
        pl.col('total_amount') < 1000,
        pl.col('congestion_surcharge') < 1000,
        pl.col('Airport_fee') < 1000
    ).filter(
        pl.col("VendorID").is_not_null(),
        pl.col("VendorID").is_in([1, 2,6,7]), #apparently these are viable
        pl.col('RatecodeID').is_not_null(),
        pl.col('RatecodeID').is_in([1, 2, 3, 4, 5, 6, 99])
    ).collect()
)

In [20]:
df.describe()

shape: (9, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ VendorID  ┆ tpep_pick ┆ tpep_drop ┆ … ┆ total_amo ┆ congestio ┆ Airport_f ┆ trip_dur │
│ ---       ┆ ---       ┆ up_dateti ┆ off_datet ┆   ┆ unt       ┆ n_surchar ┆ ee        ┆ ation    │
│ str       ┆ f64       ┆ me        ┆ ime       ┆   ┆ ---       ┆ ge        ┆ ---       ┆ ---      │
│           ┆           ┆ ---       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 2.790279e ┆ 2790279   ┆ 2790279   ┆ … ┆ 2.790279e ┆ 2.790279e ┆ 2.790279e ┆ 2.790279 │
│           ┆ 6         ┆           ┆           ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 1.767292  ┆ 2024-01-1 ┆ 2024-01-1 ┆ … ┆ 27.484175 ┆ 2.307441  ┆ 0.147693  ┆ 14.26858 │
│           ┆           ┆ 7 01:19:1 ┆ 7 01:33:5 ┆   ┆           ┆           ┆           ┆ 5        │
│           ┆           ┆ 0.908852  ┆ 6.329494  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 0.422557  ┆ null      ┆ null      ┆ … ┆ 22.282909 ┆ 0.66657   ┆ 0.486466  ┆ 11.79158 │
│ min       ┆ 1.0       ┆ 2024-01-0 ┆ 2024-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ -13.0    │
│           ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 00:00:00  ┆ 00:02:42  ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 2.0       ┆ 2024-01-0 ┆ 2024-01-0 ┆ … ┆ 15.4      ┆ 2.5       ┆ 0.0       ┆ 7.0      │
│           ┆           ┆ 9         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 15:29:06  ┆ 15:45:50  ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ 2.0       ┆ 2024-01-1 ┆ 2024-01-1 ┆ … ┆ 20.120001 ┆ 2.5       ┆ 0.0       ┆ 11.0     │
│           ┆           ┆ 7         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 10:35:20  ┆ 10:53:14  ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ 2.0       ┆ 2024-01-2 ┆ 2024-01-2 ┆ … ┆ 28.559999 ┆ 2.5       ┆ 0.0       ┆ 18.0     │
│           ┆           ┆ 4         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 18:43:41  ┆ 18:58:14  ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 2.0       ┆ 2024-02-0 ┆ 2024-02-0 ┆ … ┆ 821.0     ┆ 2.5       ┆ 1.75      ┆ 120.0    │
│           ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 00:01:15  ┆ 01:10:21  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘